<?php if ($this->message):?>
<div class="alert alert-danger">
  <?= $this->message ?>
</div>
<?php endif ?>
<form action="/" method="POST">
  <div class="form-group">
    <label for="numberOfCodes">Ilość kodów do wygenerowania</label>
    <input type="number" class="form-control" name="numberOfCodes" id="numberOfCodes" placeholder="Ilość kodów">
  </div>
  <div class="form-group">
    <label for="lenghtOfCode">Długość kodu</label>
    <input type="number" class="form-control" name="lenghtOfCode" id="lenghtOfCode" placeholder="Długość kodu">
  </div>
  <input type="hidden" name="form" value="generateCodes">
  <button type="submit" class="btn btn-primary">Generuj kody</button>
</form>
    
